### PR TITLE
Support `-mcpu` (fixes #78)

### LINKED ISSUE #78: Support for `-mcpu`
On many architectures, `-mcpu` is the functional equivalent of `-march`, and `-march` is unavailable. Nope, and there's not even a good reason as to why :)

On these architectures, GCC outputs `gcc: error: unrecognized command-line option '-march=native'; did you mean '-mcpu=native'?`, so this would be a good way to check which flag to use. 

I tried implementing this myself, but I don't know python and couldn't even figure out how to build this or run it or what to do (^: python scares me. But, I imagine it won't be tooo troublesome :D.

To test, you're welcome to have SSH access to either ppc64el or sparc64, whichever one interests you more :>

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #78

Want to try it out?:
```bash
cd "$(mktemp -d)"
git clone --branch issue-78-support-mcpu https://github.com/hartwork/resolve-march-native
cd resolve-march-native/
python3 -m venv venv  # or: virtualenv venv
source venv/bin/activate
pip install -e .
hash resolve-march-native
resolve-march-native --debug
```

### CODE REVIEW

**Comment by jlpoolen** [comment]
Note: it was extremely helpful for you to provide a simple (don't have to think) punch list -- that made it very easy for me to provide you something meaningful.  Here you go:
```

jlpoole@pizero2 /usr/local/src $ mkdir resolve-march-native
jlpoole@pizero2 /usr/local/src $ cd resolve-march-native/
jlpoole@pizero2 /usr/local/src/resolve-march-native $ ^C
jlpoole@pizero2 /usr/local/src/resolve-march-native $ git clone --branch issue-78-support-mcpu https://github.com/hartwork/resolve-march-native
Cloning into 'resolve-march-native'...
remote: Enumerating objects: 1052, done.
remote: Counting objects: 100% (420/420), done.
remote: Compressing objects: 100% (221/221), done.
remote: Total 1052 (delta 238), reused 330 (delta 199), pack-reused 632
Receiving objects: 100% (1052/1052), 196.60 KiB | 3.51 MiB/s, done.
Resolving deltas: 100% (601/601), done.
jlpoole@pizero2 /usr/local/src/resolve-march-native $ ls
resolve-march-native
jlpoole@pizero2 /usr/local/src/resolve-march-native $ cd resolve-march-native/
jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ python3 -m venv venv
jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ date
Mon Oct 30 05:50:02 PM PDT 2023
jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ source venv/bin/activate
(venv) jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ pip install -e .
Obtaining file:///usr/local/src/resolve-march-native/resolve-march-native
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: resolve-march-native
  Building editable for resolve-march-native (pyproject.toml) ... done
  Created wheel for resolve-march-native: filename=resolve_march_native-2.2.0-0.editable-py3-none-any.whl size=4019 sha256=838fd67ec6431b9dcbc42ea276059881e82036fbad989667080d43344946491e
  Stored in directory: /tmp/pip-ephem-wheel-cache-6g6oxt3o/wheels/cc/e0/0e/883e5c62eb05f661e2d5e515e8046eca5a9f8aa7d8822f7c7f
Successfully built resolve-march-native
Installing collected packages: resolve-march-native
Successfully installed resolve-march-native-2.2.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
(venv) jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ hash resolve-march-native
(venv) jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ resolve-march-native --debug
# gcc -S -fverbose-asm -o /tmp/tmpiiitxu5m/march_native.s /tmp/tmpiiitxu5m/empty.c -march=native
Flags extracted: -mabi=lp64 -mcpu=cortex-a72+crc -mlittle-endian
Flags extracted: -mabi=lp64 -march= -mbranch-protection= -mcmodel=small -mcpu=cortex-a72+crc -mfix-cortex-a53-835769 -mfix-cortex-a53-843419 -mglibc -mharden-sls= -mlittle-endian -momit-leaf-frame-pointer -moutline-atomics -moverride= -mpc-relative-literal-loads -msign-return-address=none -mstack-protector-guard-offset= -mstack-protector-guard-reg= -mstack-protector-guard=global -msve-vector-bits=scalable -mtls-dialect=desc -mtls-size=24 -mtune=
# gcc -S -fverbose-asm -o /tmp/tmpbgrkod2b/march_native.s /tmp/tmpbgrkod2b/empty.c -march=cortex-a72+crc
cc1: error: unknown value 'cortex-a72+crc' for '-march'
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8.7-a armv8.8-a armv8-r armv9-a armv9.1-a armv9.2-a armv9.3-a native
cc1: note: did you mean '-mcpu=cortex-a72+crc'?
# gcc -S -fverbose-asm -o /tmp/tmpu38qkqh0/march_native.s /tmp/tmpu38qkqh0/empty.c -mcpu=cortex-a72+crc
Flags extracted: -mabi=lp64 -mcpu=cortex-a72+crc -mlittle-endian
cc1: error: unknown value 'cortex-a72+crc' for '-march'
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8.7-a armv8.8-a armv8-r armv9-a armv9.1-a armv9.2-a armv9.3-a native
cc1: note: did you mean '-mcpu=cortex-a72+crc'?
Flags extracted: -mabi=lp64 -march= -mbranch-protection= -mcmodel=small -mcpu=cortex-a72+crc -mfix-cortex-a53-835769 -mfix-cortex-a53-843419 -mglibc -mharden-sls= -mlittle-endian -momit-leaf-frame-pointer -moutline-atomics -moverride= -mpc-relative-literal-loads -msign-return-address=none -mstack-protector-guard-offset= -mstack-protector-guard-reg= -mstack-protector-guard=global -msve-vector-bits=scalable -mtls-dialect=desc -mtls-size=24 -mtune=
-march=cortex-a72+crc
(venv) jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ 
```

**Comment by jlpoolen** [comment]
I should note, I'm on a new kernel on this unit since the time I opened a bug on this project.:

```
(venv) jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ date; uname -a
Mon Oct 30 05:54:27 PM PDT 2023
Linux pizero2 6.1.21-v8-p4 #1 SMP PREEMPT Thu Oct 26 22:23:02 PDT 2023 aarch64 GNU/Linux
(venv) jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ 

```

**Comment by hartwork** [comment]
@jlpoolen thanks for testing! The final `-march=cortex-a72+crc` indicated that something was still off: it should have read `-mcpu=cortex-a72+crc`, right? I made some correction and it should display `-mcpu=cortex-a72+crc` eventually now. Could you try the same procedure one more time and confirm that the results are now as you would expect if so? (The ppc64le machine of [GCC farm](https://portal.cfarm.net/machines/list/) that I developed against yesterday behaves slightly different (and I found none of their arm64 machines usable in practice).)

**Comment by thesamesam** [comment]
You're also very welcome to use any of the Gentoo machines for arm64/sparc/hppa/ppc/ppc64 (both BE+LE)/ia64 for both this and other bits. Just email me an SSH key or tell me to use the one from ldap.

**Comment by hartwork** [comment]
@thesamesam cool — access to actual arm64 would be nice! Python3, venv/virtualenv and GCC is all I'd need — probably all present, no need for root. The pubkey in LDAP would work well. Thanks in advance!

**Comment by thesamesam** [comment]
No problem! OK, try sping@jiji.arm.dev.gentoo.org. If you want the other boxes either now or at some other point, just let me know whenever

**Comment by hartwork** [comment]
@thesamesam for some reason it doesn't accept my key and continues asking for my password :thinking: I did check using `ssh -v [..]` that I'm using the right key and that woodpecker is happy with that same key. Any ideas?

**Comment by thesamesam** [comment]
Forgot to chown! Try now?

**Comment by hartwork** [comment]
@thesamesam works like a charm now — thanks! :pray: 

After some more fixing:

```console
$ hostname
jiji.arm.dev.gentoo.org

$ resolve-march-native
-mcpu=ares+crc+crypto+ssbs

$ git rev-parse HEAD 
3c50184e022a2d8c4b02b8904c9742b9220e4959
```

@jlpoolen I'm optimistic that it could fully work now for you as well.

**Comment by Richard-Rogalski** [comment]
Thanks!!!! <3
and thanks for the instructions I'm a python noob :D

```
(venv) dick@kapowsies ~/temp/resolve-march-native % resolve-march-native --debug
# gcc -S -fverbose-asm -o /tmp/tmpposoacil/march_native.s /tmp/tmpposoacil/empty.c -march=native
gcc: error: unrecognized command-line option '-march=native'; did you mean '-mcpu=native'?
# gcc -S -fverbose-asm -o /tmp/tmp8n3ty21r/march_native.s /tmp/tmp8n3ty21r/empty.c -mcpu=native
Flags extracted: 
gcc: error: unrecognized command-line option '-march=native'; did you mean '-mcpu=native'?
Flags extracted: -1 -G8 -ffp-contract=fast -m64 -mabi=altivec -mabi=d32 -mabi=ibmlongdouble -mabi=vec-default -maix-struct-return -malign-natural -mallow-movmisalign -maltivec -mblock-compare-inline-limit=63 -mblock-move-inline-limit=64 -mblock-ops-unaligned-vsx -mcall-linux -mcmodel=medium -mcmpb -mcpu=power8 -mcrypto -mdebug= -mdirect-move -mefficient-unaligned-vsx -mfloat128 -mfprnd -mgen-cell-microcode -mglibc -mgnu-attribute -mhard-dfp -mhard-float -mhtm -mieee128-constant -minsert-sched-nops= -mlittle -mlittle-endian -mlong-double-127 -mlra -mmfcrf -mno-fp-in-toc -mno-mfpgpr -mno-string -moptimize-swaps -mpltseq -mpointers-to-nested-functions -mpopcntb -mpopcntd -mpower8-fusion -mpower8-vector -mpowerpc -mpowerpc-gfxopt -mpowerpc-gpopt -mpowerpc64 -mprioritize-restricted-insns=1 -mquad-memory-atomic -mreadonly-in-sdata -mrecip-precision -mrecip= -mrelative-jumptables -msave-toc-indirect -msched-costly-dep= -msched-epilog -msched-prolog -msdata=none -msecure-plt -mspeculate-indirect-jumps -msplat-float-constant -msplat-word-constant -mstack-protector-guard-offset= -mstack-protector-guard-reg= -mstack-protector-guard=tls -mstring-compare-inline-limit=64 -msum-in-toc -mtls-size=32 -mtune=power8 -mupdate -mveclibabi= -mvrsave -mvsx -mvsx-timode -mwarn-altivec-long
# gcc -S -fverbose-asm -o /tmp/tmp2bz82mfd/march_native.s /tmp/tmp2bz82mfd/empty.c -march=power8
gcc: error: unrecognized command-line option '-march=power8'; did you mean '-mcpu=power8'?
# gcc -S -fverbose-asm -o /tmp/tmpl4m_hwx6/march_native.s /tmp/tmpl4m_hwx6/empty.c -mcpu=power8
Flags extracted: 
gcc: error: unrecognized command-line option '-march=power8'; did you mean '-mcpu=power8'?
Flags extracted: -1 -G8 -ffp-contract=fast -m64 -mabi=altivec -mabi=d32 -mabi=ibmlongdouble -mabi=vec-default -maix-struct-return -malign-natural -mallow-movmisalign -maltivec -mblock-compare-inline-limit=63 -mblock-move-inline-limit=64 -mblock-ops-unaligned-vsx -mcall-linux -mcmodel=medium -mcmpb -mcpu=power8 -mcrypto -mdebug= -mdirect-move -mefficient-unaligned-vsx -mfloat128 -mfprnd -mgen-cell-microcode -mglibc -mgnu-attribute -mhard-dfp -mhard-float -mhtm -mieee128-constant -minsert-sched-nops= -mlittle -mlittle-endian -mlong-double-127 -mlra -mmfcrf -mno-fp-in-toc -mno-mfpgpr -mno-string -moptimize-swaps -mpltseq -mpointers-to-nested-functions -mpopcntb -mpopcntd -mpower8-fusion -mpower8-vector -mpowerpc -mpowerpc-gfxopt -mpowerpc-gpopt -mpowerpc64 -mprioritize-restricted-insns=1 -mquad-memory-atomic -mreadonly-in-sdata -mrecip-precision -mrecip= -mrelative-jumptables -msave-toc-indirect -msched-costly-dep= -msched-epilog -msched-prolog -msdata=none -msecure-plt -mspeculate-indirect-jumps -msplat-float-constant -msplat-word-constant -mstack-protector-guard-offset= -mstack-protector-guard-reg= -mstack-protector-guard=tls -mstring-compare-inline-limit=64 -msum-in-toc -mtls-size=32 -mtune=power8 -mupdate -mveclibabi= -mvrsave -mvsx -mvsx-timode -mwarn-altivec-long
-mcpu=power8

(venv) dick@kapowsies ~/temp/resolve-march-native % which resolve-march-native 
/home/dick/temp/resolve-march-native/venv/bin/resolve-march-native

(venv) dick@kapowsies ~/temp/resolve-march-native % git status
On branch issue-78-support-mcpu
```
hmmmmmmmm.... not sure what's going on here. I know the lovely gentoo sam has offered SSH access to his boxes, but if you want to test on this machine (power8e raw ppc64le) drop me a pubkey here or by mail (rrogalski <<AT>> firemail.cc)

**Comment by hartwork** [comment]
@Richard-Rogalski thanks for trying it out! No crash and result `-mcpu=power8` seems good. I was developing these commits on a ppc64le machine of the [cfarm compile farm project](https://portal.cfarm.net/machines/list/) — `cfarm29` — so at least with regard to ppc64le (and aarch64 through @thesamesam) I'm covered for now I think, but thanks! :+1:

**Comment by jlpoolen** [comment]
Sorry to be slow in responding, I somehow missed earlier updates on this ticket and did not see any activity until a few minutes ago (2:33 PM PDT, 11/1/2023).  Here you go:

```
jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ git config pull.rebase true
jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ git pull
Successfully rebased and updated refs/heads/issue-78-support-mcpu.
jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ date;  python3 -m venv venv
Wed Nov  1 02:30:43 PM PDT 2023
jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ source venv/bin/activate
(venv) jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ pip install -e .
Obtaining file:///usr/local/src/resolve-march-native/resolve-march-native
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: resolve-march-native
  Building editable for resolve-march-native (pyproject.toml) ... done
  Created wheel for resolve-march-native: filename=resolve_march_native-2.2.0-0.editable-py3-none-any.whl size=4019 sha256=4ac12c8b5bac2bceff3f59eada73cf146de8293e852da4100c61d353c07fa63d
  Stored in directory: /tmp/pip-ephem-wheel-cache-6gpzo8rl/wheels/cc/e0/0e/883e5c62eb05f661e2d5e515e8046eca5a9f8aa7d8822f7c7f
Successfully built resolve-march-native
Installing collected packages: resolve-march-native
  Attempting uninstall: resolve-march-native
    Found existing installation: resolve-march-native 2.2.0
    Uninstalling resolve-march-native-2.2.0:
      Successfully uninstalled resolve-march-native-2.2.0
Successfully installed resolve-march-native-2.2.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
(venv) jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ hash resolve-march-native
(venv) jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ resolve-march-native --debug
# gcc -S -fverbose-asm -o /tmp/tmpp232cj6a/march_native.s /tmp/tmpp232cj6a/empty.c -march=native
Flags extracted: -mabi=lp64 -mcpu=cortex-a72+crc -mlittle-endian
Flags extracted: -mabi=lp64 -march= -mbranch-protection= -mcmodel=small -mcpu=cortex-a72+crc -mfix-cortex-a53-835769 -mfix-cortex-a53-843419 -mglibc -mharden-sls= -mlittle-endian -momit-leaf-frame-pointer -moutline-atomics -moverride= -mpc-relative-literal-loads -msign-return-address=none -mstack-protector-guard-offset= -mstack-protector-guard-reg= -mstack-protector-guard=global -msve-vector-bits=scalable -mtls-dialect=desc -mtls-size=24 -mtune=
# gcc -S -fverbose-asm -o /tmp/tmpbo_gb1_d/march_native.s /tmp/tmpbo_gb1_d/empty.c -march=cortex-a72+crc
cc1: error: unknown value 'cortex-a72+crc' for '-march'
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8.7-a armv8.8-a armv8-r armv9-a armv9.1-a armv9.2-a armv9.3-a native
cc1: note: did you mean '-mcpu=cortex-a72+crc'?
# gcc -S -fverbose-asm -o /tmp/tmp_uxba2uw/march_native.s /tmp/tmp_uxba2uw/empty.c -mcpu=cortex-a72+crc
Flags extracted: -mabi=lp64 -mcpu=cortex-a72+crc -mlittle-endian
cc1: error: unknown value 'cortex-a72+crc' for '-march'
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8.7-a armv8.8-a armv8-r armv9-a armv9.1-a armv9.2-a armv9.3-a native
cc1: note: did you mean '-mcpu=cortex-a72+crc'?
Flags extracted: -mabi=lp64 -march= -mbranch-protection= -mcmodel=small -mcpu=cortex-a72+crc -mfix-cortex-a53-835769 -mfix-cortex-a53-843419 -mglibc -mharden-sls= -mlittle-endian -momit-leaf-frame-pointer -moutline-atomics -moverride= -mpc-relative-literal-loads -msign-return-address=none -mstack-protector-guard-offset= -mstack-protector-guard-reg= -mstack-protector-guard=global -msve-vector-bits=scalable -mtls-dialect=desc -mtls-size=24 -mtune=
-mcpu=cortex-a72+crc
(venv) jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ git log |head
commit 3c50184e022a2d8c4b02b8904c9742b9220e4959
Author: Sebastian Pipping <sebastian@pipping.org>
Date:   Tue Oct 31 13:43:45 2023 +0100

    Only forward stderr with --debug

commit 77f7ccb67635ce9efe20c5946344fd07006642ff
Author: Sebastian Pipping <sebastian@pipping.org>
Date:   Tue Oct 31 00:16:39 2023 +0100

(venv) jlpoole@pizero2 /usr/local/src/resolve-march-native/resolve-march-native $ 

```

**Comment by hartwork** [comment]
@jlpoolen looks good to me, thanks! :+1: I'll wait for one other person's results a bit more and then decide if it's good enough to merge. With some luck this week.

CC @Richard-Rogalski

**Comment by medanisjbara** [comment]
Hello @hartwork,
I was wondering, instead of `try [..] except [..]` blocks, wouldn't it be better if the runner can do a run and extract the `options passed` from the comment in `march_native.s` to set `march_wanted` ? in this case `march_wanted` can become an attribute to the engine and we can get rid of `gcc: error: unrecognized command-line option '-march=native'; did you mean '-mcpu=native'?` in debug output caused by the failed `subprocess.check_output` call in the `try [..] except [..]` block.

**Comment by hartwork** [comment]
@medanisjbara you have a point there, it is a bit of a hack, but I would rather first do a release with the version that multiple people tested and then do a new iteration to improve with a previous release working to fall back on as an option in case it goes wrong. GCC varies quite a bit across platforms in when it wants `-march` and when `-mcpu` and the current approach while a bit dirty is likely the one with widest support. If I find time I should clean up this code a bit more in general also.

**Comment by medanisjbara** [comment]
Understood, can you provide what do you intend to do ? I mean what did you mean by
> I should clean up this code a bit more in general also

I would like to contribute if possible 😅

**Comment by hartwork** [comment]
@medanisjbara thanks for your interest, I have reached out to you via e-mail just now.

**Pull request merged**
